# ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    ds:
      # ?????
      master:
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: th123456
      # ?????
      slave:
        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: th123456
      # ?????
    initialSize: 5
    # ???????
    minIdle: 10
    # ???????
    maxActive: 20
    # ?????????????
    maxWait: 60000
    # ???????????????????????????????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????????
    minEvictableIdleTimeMillis: 300000
    # ??????????????????????
    maxEvictableIdleTimeMillis: 900000
    # ??????????
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      # ???????????????
      allow:
      url-pattern: /druid/*
      # ???????????
      login-username: tienchin
      login-password: 123456
    filter:
      stat:
        enabled: true
        # ?SQL??
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: tru